Repository FRONTENDBOOTCAMP-11th/febc11-vanilla-under30y, pull requests merged in 2024-10, with the labels that each got.

#47 제품 상세 페이지 디테일 개선
  .vscode/settings.json
  src/AboutProduct/test.js
  src/productDetail/productDetail.css
  src/productDetail/productDetail.html
  src/productDetail/script.js
  src/productDetail/writeReview.css
  src/productDetail/writeReview.html
Labels: enhancement

#61 Feature/member api
  .vscode/settings.json
  package-lock.json
  package.json
  src/features/member/authority.html
  src/features/member/authoritystyle.css
  src/features/member/login.html
  src/features/member/login.js
  src/features/member/loginstyle.css
  src/features/member/signup.html
  src/features/member/signup.js
  src/features/member/signupstyle.css
  src/features/member/validate.js
Labels: enhancement

#63 Feature/product list 필터 기능 추가
  api/vanilla-nike/bruno.json
  package-lock.json
  src/features/item/itemList.css
  src/features/item/itemList.html
  src/features/item/itemList.js
  src/features/member/login.js
Labels: enhancement

#66 코드 정리 및 문제점 해결 - 스크롤 미적용, 이미지 로딩 전 공간 확보
  src/features/item/itemDetail.css
  src/features/item/itemDetail.html
  src/features/item/itemDetail.js
  src/features/item/itemDetailAddtional.js
  src/features/item/ui-template-itemDetail.html
Labels: bug, enhancement

#67 Yoon upload
  src/assets/icons/carticon/likeIcon.svg
  src/assets/icons/carticon/subtotalDetail.svg
  src/features/cart/prdBasket.html
  src/features/cart/prdBasket.js
  src/features/cart/style.css
Labels: enhancement

#74 fix/장바구니 이동 관련 수정 및 login.js에서 accessToken 문제 해결
  src/features/item/itemDetail.js
  src/features/member/login.js
Labels: bug
